name: Azure Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name myacr   # Replace 'myacr' with your ACR name

    - name: Build and push Docker images
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --push -t myacr.azurecr.io/frontend:latest ./frontend
        docker buildx build --platform linux/amd64,linux/arm64 --push -t myacr.azurecr.io/backend:latest ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy frontend to Azure Container Instances
      run: |
        if az container show --name frontend --resource-group <your_resource_group> > /dev/null 2>&1; then
          az container update --name frontend --resource-group <your_resource_group> --image myacr.azurecr.io/frontend:latest
        else
          az container create --resource-group <your_resource_group> --name frontend --image myacr.azurecr.io/frontend:latest --cpu 1 --memory 1 --registry-login-server myacr.azurecr.io --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }}
        fi

    - name: Deploy backend to Azure Container Instances
      run: |
        if az container show --name backend --resource-group <your_resource_group> > /dev/null 2>&1; then
          az container update --name backend --resource-group <your_resource_group> --image myacr.azurecr.io/backend:latest
        else
          az container create --resource-group <your_resource_group> --name backend --image myacr.azurecr.io/backend:latest --cpu 1 --memory 1 --registry-login-server myacr.azurecr.io --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }}
        fi
