# Use an official Node.js runtime as a parent image
FROM node:20-alpine
# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port (e.g., 5000)
EXPOSE 5000

# Command to run the app
CMD ["node", "server.js"]
