name: Azure Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        docker login TimTrevRegistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --push -t TimTrevRegistry.azurecr.io/frontend:latest ./frontend
        docker buildx build --platform linux/amd64,linux/arm64 --push -t TimTrevRegistry.azurecr.io/backend:latest ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        docker login TimTrevRegistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

    - name: Deploy frontend to Azure Container Instances
      run: |
          az container create --resource-group DefaultGroup --name frontend --image TimTrevRegistry.azurecr.io/frontend:latest --cpu 1 --memory 1 --registry-login-server TimTrevRegistry.azurecr.io --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }}

    - name: Deploy backend to Azure Container Instances
      run: |
          az container create --resource-group DefaultGroup --name backend --image TimTrevRegistry.azurecr.io/backend:latest --cpu 1 --memory 1 --registry-login-server TimTrevRegistry.azurecr.io --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }}